### ISSUE TITLE
user pages show log out option even if not logged in

### ISSUE THREAD

**Issue by cheollie** [wlmac/metropolis#71] opened 2021-10-05 02:40 UTC
When you view a user while not logged in, there will be an option to logout on the sidebar. (Not sure if this is a bug or not/intended but just reported it anyway.)

**Comment by hillcrestpaul0719** [comment] 2021-10-05 02:49
Duplicate of #45, thanks for reporting though 👍🏼

**Closed by hillcrestpaul0719** 2021-10-05 02:49 UTC
Labels: bug, duplicate
